name: Docker Images

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        app: [core, tasmota-connector]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker images
      run: docker build --build-arg APP=${{ matrix.app }} --tag seeseemelk/hobo-${{ matrix.app }}:snapshot .
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOWKER_PASSWORD }}
        
    - name: Push Docker images
      run: docker push seeseemelk/hobo-${{ matrix.app }}:snapshot
