name: Docker Native Images

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        app: [core]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
      with:
        platforms: amd64,arm64

    - name: Get version to publish
      uses: damienaicheh/extract-version-from-tag-action@v1.0.0

    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create Docker builder
      run: docker buildx create --use

    - name: Build Docker images
      run: |
        docker buildx build --push --platform=amd64,arm64 --build-arg APP=${{ matrix.app }} -f docker.native --tag seeseemelk/hobo-${{ matrix.app }}:latest .
        docker buildx build --push --platform=amd64,arm64 --build-arg APP=${{ matrix.app }} -f docker.native --tag seeseemelk/hobo-${{ matrix.app }}:$MAJOR .
        docker buildx build --push --platform=amd64,arm64 --build-arg APP=${{ matrix.app }} -f docker.native --tag seeseemelk/hobo-${{ matrix.app }}:$MAJOR.$MINOR .
        docker buildx build --push --platform=amd64,arm64 --build-arg APP=${{ matrix.app }} -f docker.native --tag seeseemelk/hobo-${{ matrix.app }}:$MAJOR.$MINOR.$PATCH .
